name: Build Check

on:
    push:
        branches: [ "master" ]
        paths-ignore:
            - 'README.md'
            - '.gitignore'
            - 'LICENSE'

jobs:
    build:
        name: Build Check
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install deps
          run: sudo apt install make gcc gcc-mingw-w64 g++
        
        - name: Build Linux
          run: make build
          
        - name: Build Windows
          run: make windows

        - name: Upload Linux Artifact
          uses: actions/upload-artifact@v4
          with:
            name: linux
            path: ./bin/ip_scanner

        - name: Upload Windows Artifact
          uses: actions/upload-artifact@v4
          with:
            name: windows
            path: ./bin/ip_scanner.exe